name: Deploy new application version

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Sets RELEASE_VERSION to be refs/tags/v<version> -> <version>
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF#refs/tags/v})
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Merge tag to master
      run: |
        git checkout master
        git merge ${GITHUB_REF}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
    - name: Install dependencies
      run: |
        sudo apt-get install pandoc graphviz xdot
        python -m pip install --upgrade pip
        pip install setuptools wheel twine pypandoc
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        echo "Pushing version ${{ env.RELEASE_VERSION }}"
        echo "__version__ = '${{ env.RELEASE_VERSION }}'" >> hooker/__init__.py
        python setup.py sdist bdist_wheel
        twine upload dist/*
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@0.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pre-build-command: "pip install -e . && pip install -r docs/.requirements.txt"
        build-command: "sphinx-build -b html . _build"
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.SPHINX_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/_build
