name: Execute tests with pytest (Python 2)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2
      uses: actions/setup-python@v1
      with:
        python-version: 2.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
